### ISSUE TITLE
Auto-update from official database

### ISSUE THREAD

**Issue by szepeviktor** [PrinsFrank/standards#1]
Were you thinking about updating from/checking against the official database of each standard?

**Comment by PrinsFrank** [comment]
> Were you thinking about updating from/checking against the official database of each standard?

Yes, for sure! As I'm on holiday until July 1st without a laptop it won't happen in the next few weeks, but it was my intention to add. You're free to join if you want!

**Comment by szepeviktor** [comment]
Please bring CHF 300 when you return home!

https://www.iso.org/publication/PUB500001.html

**Comment by PrinsFrank** [comment]
@szepeviktor Yes, I didn't close it yet as now it is also readible code and all specs are implemented. ;)
