### ISSUE TITLE
Handle double keys

### ISSUE THREAD

**Issue by szepeviktor** [PrinsFrank/standards#182]
Lets say we have a latin key and a transliterated key.
Both of them end up being the same.
```php
    case ru = 'рф';
    case ru = 'ru';
```

What happens then?

**Comment by szepeviktor** [comment]
- dropped
- overwritten
- Exception 👈🏻

**Comment by PrinsFrank** [comment]
@szepeviktor as mentioned in in #183, it seems that enum cases with duplicate names get dropped. I proposed a solution in the linked PR. What do you think?

**Comment by PrinsFrank** [comment]
FYI: there's currently no location the EnumTestCase would make sense in, so you can move the files from `tests/Unit/` to `tests/src/Unit` and add a new `tests/dev` folder I guess?

**Comment by PrinsFrank** [comment]
Fixed by #200
