### ISSUE TITLE
IANA Assigned Ports and services

### ISSUE THREAD

**Issue by Jellyfrog** [PrinsFrank/standards#2]
Not an ISO standard but IANA, but ports would be a good addition;

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv

**Comment by PrinsFrank** [comment]
> Not an ISO standard but IANA, but ports would be a good addition;
> 
> https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt
> 
> https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv

I will definitely look into this when I get back from holiday!

**Comment by PrinsFrank** [comment]
Hi @Jellyfrog, I am sorry but for a spec to be able to converted, both the keys and values have to be unique within in a standard. I don't see a way to implement this as an enum, so I am going to close this issue. If you do have a way and are willing to implement, you are welcome to submit a PR!
