### ISSUE TITLE
README for Language Tags is missing

### ISSUE THREAD

**Issue by szepeviktor** [PrinsFrank/standards#234]
https://github.com/PrinsFrank/standards/blob/b7cf95c2eaf99a743b6b34d2d134a2a093a2af4e/README.md?plain=1#L693-L695

No content.

**Comment by PrinsFrank** [comment]
@szepeviktor I forgot about that, It's quite some work though. Will pick this up in a while!

**Comment by szepeviktor** [comment]
@github-actions No, no. It is not the issue, it is Frank 🙃
