### ISSUE TITLE
[Feature Request] E.123 / E.124 / Country calling codes

### ISSUE THREAD

**Issue by francoisauclair911** [PrinsFrank/standards#7]
Hi, 

Would you be interested in adding international calling code to your library ? I would gladly contribute a PR.

We could add methods on the enum to get the `ISO3166_1_Alpha_3` and `ISO3166_1_Alpha_2` from the country code and vice versa

Relevant links
- [Wikipedia - International call prefix (IDD)](https://en.wikipedia.org/wiki/International_call_prefix)
- [Wikipedia - E.123](https://en.wikipedia.org/wiki/E.123)
- [Wikipedia - E.164](https://en.wikipedia.org/wiki/E.164)

**Comment by PrinsFrank** [comment]
Sounds good! If you want to add a PR you're more than welcome!
